/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as ProjectDetailsRouteImport } from './routes/project-details'
import { Route as ProjectAuditRouteImport } from './routes/project-audit'
import { Route as BuildForMeRouteImport } from './routes/build-for-me'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectssIndexRouteImport } from './routes/projectss/index'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectDetailsRoute = ProjectDetailsRouteImport.update({
  id: '/project-details',
  path: '/project-details',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectAuditRoute = ProjectAuditRouteImport.update({
  id: '/project-audit',
  path: '/project-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildForMeRoute = BuildForMeRouteImport.update({
  id: '/build-for-me',
  path: '/build-for-me',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectssIndexRoute = ProjectssIndexRouteImport.update({
  id: '/projectss/',
  path: '/projectss/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/build-for-me': typeof BuildForMeRoute
  '/project-audit': typeof ProjectAuditRoute
  '/project-details': typeof ProjectDetailsRoute
  '/resources': typeof ResourcesRoute
  '/services': typeof ServicesRoute
  '/projectss/': typeof ProjectssIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/build-for-me': typeof BuildForMeRoute
  '/project-audit': typeof ProjectAuditRoute
  '/project-details': typeof ProjectDetailsRoute
  '/resources': typeof ResourcesRoute
  '/services': typeof ServicesRoute
  '/projectss': typeof ProjectssIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/build-for-me': typeof BuildForMeRoute
  '/project-audit': typeof ProjectAuditRoute
  '/project-details': typeof ProjectDetailsRoute
  '/resources': typeof ResourcesRoute
  '/services': typeof ServicesRoute
  '/projectss/': typeof ProjectssIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/build-for-me'
    | '/project-audit'
    | '/project-details'
    | '/resources'
    | '/services'
    | '/projectss/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/build-for-me'
    | '/project-audit'
    | '/project-details'
    | '/resources'
    | '/services'
    | '/projectss'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/build-for-me'
    | '/project-audit'
    | '/project-details'
    | '/resources'
    | '/services'
    | '/projectss/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BuildForMeRoute: typeof BuildForMeRoute
  ProjectAuditRoute: typeof ProjectAuditRoute
  ProjectDetailsRoute: typeof ProjectDetailsRoute
  ResourcesRoute: typeof ResourcesRoute
  ServicesRoute: typeof ServicesRoute
  ProjectssIndexRoute: typeof ProjectssIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project-details': {
      id: '/project-details'
      path: '/project-details'
      fullPath: '/project-details'
      preLoaderRoute: typeof ProjectDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project-audit': {
      id: '/project-audit'
      path: '/project-audit'
      fullPath: '/project-audit'
      preLoaderRoute: typeof ProjectAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/build-for-me': {
      id: '/build-for-me'
      path: '/build-for-me'
      fullPath: '/build-for-me'
      preLoaderRoute: typeof BuildForMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projectss/': {
      id: '/projectss/'
      path: '/projectss'
      fullPath: '/projectss/'
      preLoaderRoute: typeof ProjectssIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BuildForMeRoute: BuildForMeRoute,
  ProjectAuditRoute: ProjectAuditRoute,
  ProjectDetailsRoute: ProjectDetailsRoute,
  ResourcesRoute: ResourcesRoute,
  ServicesRoute: ServicesRoute,
  ProjectssIndexRoute: ProjectssIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
